version: "3"

tasks:
  db-generate:
    cmds:
      - go run github.com/steebchen/prisma-client-go generate --schema=./db/schema.prisma
    silent: true
  db-push:
    cmds:
      - go run github.com/steebchen/prisma-client-go db push --schema=./db/schema.prisma
    silent: true
  db-pull:
    cmds:
      - go run github.com/steebchen/prisma-client-go db pull --schema=./db/schema.prisma
    silent: true
  db-migrate:
    cmds:
      - go run github.com/steebchen/prisma-client-go migrate dev --schema=./db/schema.prisma
    silent: true
  db-deploy:
    cmds:
      - go run github.com/steebchen/prisma-client-go migrate deploy --schema=./db/schema.prisma
    silent: true
