name: Main CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate Prisma Client
        run: go run github.com/steebchen/prisma-client-go generate --schema=./schema.prisma

      - name: Run Tests
        run: go test ./...

      - name: Deploy
        run: railway up --service "Search Engine"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
